package com.example.snake.presentation

fun snakeSplash(viewModel: GameViewModel) {
    viewModel.setPixel(0, 0, filled)
    viewModel.setPixel(0, 1, filled)
    viewModel.setPixel(0, 2, filled)
    viewModel.setPixel(0, 3, filled)
    viewModel.setPixel(0, 4, filled)
    viewModel.setPixel(0, 5, filled)
    viewModel.setPixel(0, 6, filled)
    viewModel.setPixel(0, 7, filled)
    viewModel.setPixel(0, 8, filled)
    viewModel.setPixel(0, 9, filled)
    viewModel.setPixel(0, 10, filled)
    viewModel.setPixel(0, 11, filled)
    viewModel.setPixel(0, 12, filled)
    viewModel.setPixel(0, 13, filled)
    viewModel.setPixel(0, 14, filled)
    viewModel.setPixel(0, 15, filled)
    viewModel.setPixel(0, 16, filled)
    viewModel.setPixel(0, 17, filled)
    viewModel.setPixel(0, 18, filled)
    viewModel.setPixel(0, 19, filled)
    viewModel.setPixel(0, 20, filled)
    viewModel.setPixel(1, 0, filled)
    viewModel.setPixel(1, 1, filled)
    viewModel.setPixel(1, 2, filled)
    viewModel.setPixel(1, 3, filled)
    viewModel.setPixel(1, 4, filled)
    viewModel.setPixel(1, 5, filled)
    viewModel.setPixel(1, 6, filled)
    viewModel.setPixel(1, 7, filled)
    viewModel.setPixel(1, 8, filled)
    viewModel.setPixel(1, 9, filled)
    viewModel.setPixel(1, 10, filled)
    viewModel.setPixel(1, 11, filled)
    viewModel.setPixel(1, 12, filled)
    viewModel.setPixel(1, 13, filled)
    viewModel.setPixel(1, 14, filled)
    viewModel.setPixel(1, 15, filled)
    viewModel.setPixel(1, 16, filled)
    viewModel.setPixel(1, 17, filled)
    viewModel.setPixel(1, 18, filled)
    viewModel.setPixel(1, 19, filled)
    viewModel.setPixel(1, 20, filled)
    viewModel.setPixel(2, 0, filled)
    viewModel.setPixel(2, 1, filled)
    viewModel.setPixel(2, 2, filled)
    viewModel.setPixel(2, 3, filled)
    viewModel.setPixel(2, 4, filled)
    viewModel.setPixel(2, 5, filled)
    viewModel.setPixel(2, 6, filled)
    viewModel.setPixel(2, 7, filled)
    viewModel.setPixel(2, 8, filled)
    viewModel.setPixel(2, 9, filled)
    viewModel.setPixel(2, 14, filled)
    viewModel.setPixel(2, 15, filled)
    viewModel.setPixel(2, 16, filled)
    viewModel.setPixel(2, 17, filled)
    viewModel.setPixel(2, 18, filled)
    viewModel.setPixel(2, 19, filled)
    viewModel.setPixel(2, 20, filled)
    viewModel.setPixel(3, 0, filled)
    viewModel.setPixel(3, 1, filled)
    viewModel.setPixel(3, 2, filled)
    viewModel.setPixel(3, 3, filled)
    viewModel.setPixel(3, 4, filled)
    viewModel.setPixel(3, 5, filled)
    viewModel.setPixel(3, 10, filled)
    viewModel.setPixel(3, 11, filled)
    viewModel.setPixel(3, 12, filled)
    viewModel.setPixel(3, 13, filled)
    viewModel.setPixel(3, 16, filled)
    viewModel.setPixel(3, 17, filled)
    viewModel.setPixel(3, 18, filled)
    viewModel.setPixel(3, 19, filled)
    viewModel.setPixel(3, 20, filled)
    viewModel.setPixel(4, 0, filled)
    viewModel.setPixel(4, 1, filled)
    viewModel.setPixel(4, 2, filled)
    viewModel.setPixel(4, 3, filled)
    viewModel.setPixel(4, 4, filled)
    viewModel.setPixel(4, 6, filled)
    viewModel.setPixel(4, 7, filled)
    viewModel.setPixel(4, 8, filled)
    viewModel.setPixel(4, 9, filled)
    viewModel.setPixel(4, 10, filled)
    viewModel.setPixel(4, 11, filled)
    viewModel.setPixel(4, 12, filled)
    viewModel.setPixel(4, 13, filled)
    viewModel.setPixel(4, 14, filled)
    viewModel.setPixel(4, 15, filled)
    viewModel.setPixel(4, 17, filled)
    viewModel.setPixel(4, 18, filled)
    viewModel.setPixel(4, 19, filled)
    viewModel.setPixel(4, 20, filled)
    viewModel.setPixel(5, 0, filled)
    viewModel.setPixel(5, 1, filled)
    viewModel.setPixel(5, 2, filled)
    viewModel.setPixel(5, 3, filled)
    viewModel.setPixel(5, 4, filled)
    viewModel.setPixel(5, 13, filled)
    viewModel.setPixel(5, 14, filled)
    viewModel.setPixel(5, 15, filled)
    viewModel.setPixel(5, 16, filled)
    viewModel.setPixel(5, 18, filled)
    viewModel.setPixel(5, 19, filled)
    viewModel.setPixel(5, 20, filled)
    viewModel.setPixel(6, 0, filled)
    viewModel.setPixel(6, 1, filled)
    viewModel.setPixel(6, 2, filled)
    viewModel.setPixel(6, 3, filled)
    viewModel.setPixel(6, 5, filled)
    viewModel.setPixel(6, 6, filled)
    viewModel.setPixel(6, 7, filled)
    viewModel.setPixel(6, 11, filled)
    viewModel.setPixel(6, 12, filled)
    viewModel.setPixel(6, 14, filled)
    viewModel.setPixel(6, 15, filled)
    viewModel.setPixel(6, 16, filled)
    viewModel.setPixel(6, 18, filled)
    viewModel.setPixel(6, 19, filled)
    viewModel.setPixel(6, 20, filled)
    viewModel.setPixel(7, 0, filled)
    viewModel.setPixel(7, 1, filled)
    viewModel.setPixel(7, 2, filled)
    viewModel.setPixel(7, 4, filled)
    viewModel.setPixel(7, 5, filled)
    viewModel.setPixel(7, 6, filled)
    viewModel.setPixel(7, 7, filled)
    viewModel.setPixel(7, 8, filled)
    viewModel.setPixel(7, 10, filled)
    viewModel.setPixel(7, 11, filled)
    viewModel.setPixel(7, 12, filled)
    viewModel.setPixel(7, 13, filled)
    viewModel.setPixel(7, 15, filled)
    viewModel.setPixel(7, 16, filled)
    viewModel.setPixel(7, 18, filled)
    viewModel.setPixel(7, 19, filled)
    viewModel.setPixel(7, 20, filled)
    viewModel.setPixel(8, 0, filled)
    viewModel.setPixel(8, 1, filled)
    viewModel.setPixel(8, 3, filled)
    viewModel.setPixel(8, 4, filled)
    viewModel.setPixel(8, 5, filled)
    viewModel.setPixel(8, 6, filled)
    viewModel.setPixel(8, 7, filled)
    viewModel.setPixel(8, 8, filled)
    viewModel.setPixel(8, 9, filled)
    viewModel.setPixel(8, 11, filled)
    viewModel.setPixel(8, 12, filled)
    viewModel.setPixel(8, 13, filled)
    viewModel.setPixel(8, 15, filled)
    viewModel.setPixel(8, 16, filled)
    viewModel.setPixel(8, 18, filled)
    viewModel.setPixel(8, 19, filled)
    viewModel.setPixel(8, 20, filled)
    viewModel.setPixel(9, 0, filled)
    viewModel.setPixel(9, 1, filled)
    viewModel.setPixel(9, 3, filled)
    viewModel.setPixel(9, 4, filled)
    viewModel.setPixel(9, 5, filled)
    viewModel.setPixel(9, 6, filled)
    viewModel.setPixel(9, 7, filled)
    viewModel.setPixel(9, 8, filled)
    viewModel.setPixel(9, 9, filled)
    viewModel.setPixel(9, 10, filled)
    viewModel.setPixel(9, 12, filled)
    viewModel.setPixel(9, 13, filled)
    viewModel.setPixel(9, 15, filled)
    viewModel.setPixel(9, 16, filled)
    viewModel.setPixel(9, 18, filled)
    viewModel.setPixel(9, 19, filled)
    viewModel.setPixel(9, 20, filled)
    viewModel.setPixel(10, 0, filled)
    viewModel.setPixel(10, 1, filled)
    viewModel.setPixel(10, 3, filled)
    viewModel.setPixel(10, 6, filled)
    viewModel.setPixel(10, 8, filled)
    viewModel.setPixel(10, 9, filled)
    viewModel.setPixel(10, 10, filled)
    viewModel.setPixel(10, 12, filled)
    viewModel.setPixel(10, 13, filled)
    viewModel.setPixel(10, 15, filled)
    viewModel.setPixel(10, 16, filled)
    viewModel.setPixel(10, 18, filled)
    viewModel.setPixel(10, 19, filled)
    viewModel.setPixel(10, 20, filled)
    viewModel.setPixel(11, 0, filled)
    viewModel.setPixel(11, 1, filled)
    viewModel.setPixel(11, 3, filled)
    viewModel.setPixel(11, 6, filled)
    viewModel.setPixel(11, 8, filled)
    viewModel.setPixel(11, 9, filled)
    viewModel.setPixel(11, 10, filled)
    viewModel.setPixel(11, 12, filled)
    viewModel.setPixel(11, 13, filled)
    viewModel.setPixel(11, 15, filled)
    viewModel.setPixel(11, 16, filled)
    viewModel.setPixel(11, 18, filled)
    viewModel.setPixel(11, 19, filled)
    viewModel.setPixel(11, 20, filled)
    viewModel.setPixel(12, 0, filled)
    viewModel.setPixel(12, 1, filled)
    viewModel.setPixel(12, 2, filled)
    viewModel.setPixel(12, 4, filled)
    viewModel.setPixel(12, 5, filled)
    viewModel.setPixel(12, 6, filled)
    viewModel.setPixel(12, 9, filled)
    viewModel.setPixel(12, 11, filled)
    viewModel.setPixel(12, 12, filled)
    viewModel.setPixel(12, 13, filled)
    viewModel.setPixel(12, 15, filled)
    viewModel.setPixel(12, 16, filled)
    viewModel.setPixel(12, 18, filled)
    viewModel.setPixel(12, 19, filled)
    viewModel.setPixel(12, 20, filled)
    viewModel.setPixel(13, 0, filled)
    viewModel.setPixel(13, 1, filled)
    viewModel.setPixel(13, 2, filled)
    viewModel.setPixel(13, 4, filled)
    viewModel.setPixel(13, 5, filled)
    viewModel.setPixel(13, 6, filled)
    viewModel.setPixel(13, 8, filled)
    viewModel.setPixel(13, 10, filled)
    viewModel.setPixel(13, 11, filled)
    viewModel.setPixel(13, 12, filled)
    viewModel.setPixel(13, 14, filled)
    viewModel.setPixel(13, 15, filled)
    viewModel.setPixel(13, 16, filled)
    viewModel.setPixel(13, 18, filled)
    viewModel.setPixel(13, 19, filled)
    viewModel.setPixel(13, 20, filled)
    viewModel.setPixel(14, 0, filled)
    viewModel.setPixel(14, 1, filled)
    viewModel.setPixel(14, 2, filled)
    viewModel.setPixel(14, 3, filled)
    viewModel.setPixel(14, 5, filled)
    viewModel.setPixel(14, 6, filled)
    viewModel.setPixel(14, 8, filled)
    viewModel.setPixel(14, 10, filled)
    viewModel.setPixel(14, 11, filled)
    viewModel.setPixel(14, 13, filled)
    viewModel.setPixel(14, 14, filled)
    viewModel.setPixel(14, 15, filled)
    viewModel.setPixel(14, 16, filled)
    viewModel.setPixel(14, 18, filled)
    viewModel.setPixel(14, 19, filled)
    viewModel.setPixel(14, 20, filled)
    viewModel.setPixel(15, 0, filled)
    viewModel.setPixel(15, 1, filled)
    viewModel.setPixel(15, 2, filled)
    viewModel.setPixel(15, 3, filled)
    viewModel.setPixel(15, 4, filled)
    viewModel.setPixel(15, 8, filled)
    viewModel.setPixel(15, 9, filled)
    viewModel.setPixel(15, 12, filled)
    viewModel.setPixel(15, 13, filled)
    viewModel.setPixel(15, 14, filled)
    viewModel.setPixel(15, 15, filled)
    viewModel.setPixel(15, 17, filled)
    viewModel.setPixel(15, 18, filled)
    viewModel.setPixel(15, 19, filled)
    viewModel.setPixel(15, 20, filled)
    viewModel.setPixel(16, 0, filled)
    viewModel.setPixel(16, 1, filled)
    viewModel.setPixel(16, 2, filled)
    viewModel.setPixel(16, 3, filled)
    viewModel.setPixel(16, 4, filled)
    viewModel.setPixel(16, 5, filled)
    viewModel.setPixel(16, 6, filled)
    viewModel.setPixel(16, 8, filled)
    viewModel.setPixel(16, 9, filled)
    viewModel.setPixel(16, 10, filled)
    viewModel.setPixel(16, 12, filled)
    viewModel.setPixel(16, 13, filled)
    viewModel.setPixel(16, 14, filled)
    viewModel.setPixel(16, 16, filled)
    viewModel.setPixel(16, 17, filled)
    viewModel.setPixel(16, 18, filled)
    viewModel.setPixel(16, 19, filled)
    viewModel.setPixel(16, 20, filled)
    viewModel.setPixel(17, 0, filled)
    viewModel.setPixel(17, 1, filled)
    viewModel.setPixel(17, 2, filled)
    viewModel.setPixel(17, 3, filled)
    viewModel.setPixel(17, 4, filled)
    viewModel.setPixel(17, 5, filled)
    viewModel.setPixel(17, 7, filled)
    viewModel.setPixel(17, 9, filled)
    viewModel.setPixel(17, 10, filled)
    viewModel.setPixel(17, 11, filled)
    viewModel.setPixel(17, 15, filled)
    viewModel.setPixel(17, 16, filled)
    viewModel.setPixel(17, 17, filled)
    viewModel.setPixel(17, 18, filled)
    viewModel.setPixel(17, 19, filled)
    viewModel.setPixel(17, 20, filled)
    viewModel.setPixel(18, 0, filled)
    viewModel.setPixel(18, 1, filled)
    viewModel.setPixel(18, 2, filled)
    viewModel.setPixel(18, 3, filled)
    viewModel.setPixel(18, 4, filled)
    viewModel.setPixel(18, 5, filled)
    viewModel.setPixel(18, 6, filled)
    viewModel.setPixel(18, 7, filled)
    viewModel.setPixel(18, 8, filled)
    viewModel.setPixel(18, 9, filled)
    viewModel.setPixel(18, 10, filled)
    viewModel.setPixel(18, 11, filled)
    viewModel.setPixel(18, 12, filled)
    viewModel.setPixel(18, 13, filled)
    viewModel.setPixel(18, 14, filled)
    viewModel.setPixel(18, 15, filled)
    viewModel.setPixel(18, 16, filled)
    viewModel.setPixel(18, 17, filled)
    viewModel.setPixel(18, 18, filled)
    viewModel.setPixel(18, 19, filled)
    viewModel.setPixel(18, 20, filled)
    viewModel.setPixel(19, 0, filled)
    viewModel.setPixel(19, 1, filled)
    viewModel.setPixel(19, 2, filled)
    viewModel.setPixel(19, 3, filled)
    viewModel.setPixel(19, 4, filled)
    viewModel.setPixel(19, 5, filled)
    viewModel.setPixel(19, 6, filled)
    viewModel.setPixel(19, 7, filled)
    viewModel.setPixel(19, 8, filled)
    viewModel.setPixel(19, 9, filled)
    viewModel.setPixel(19, 10, filled)
    viewModel.setPixel(19, 11, filled)
    viewModel.setPixel(19, 12, filled)
    viewModel.setPixel(19, 13, filled)
    viewModel.setPixel(19, 14, filled)
    viewModel.setPixel(19, 15, filled)
    viewModel.setPixel(19, 16, filled)
    viewModel.setPixel(19, 17, filled)
    viewModel.setPixel(19, 18, filled)
    viewModel.setPixel(19, 19, filled)
    viewModel.setPixel(19, 20, filled)
    viewModel.setPixel(20, 0, filled)
    viewModel.setPixel(20, 1, filled)
    viewModel.setPixel(20, 2, filled)
    viewModel.setPixel(20, 3, filled)
    viewModel.setPixel(20, 4, filled)
    viewModel.setPixel(20, 5, filled)
    viewModel.setPixel(20, 6, filled)
    viewModel.setPixel(20, 7, filled)
    viewModel.setPixel(20, 8, filled)
    viewModel.setPixel(20, 9, filled)
    viewModel.setPixel(20, 10, filled)
    viewModel.setPixel(20, 11, filled)
    viewModel.setPixel(20, 12, filled)
    viewModel.setPixel(20, 13, filled)
    viewModel.setPixel(20, 14, filled)
    viewModel.setPixel(20, 15, filled)
    viewModel.setPixel(20, 16, filled)
    viewModel.setPixel(20, 17, filled)
    viewModel.setPixel(20, 18, filled)
    viewModel.setPixel(20, 19, filled)
    viewModel.setPixel(20, 20, filled)
}

fun snakeSplashInverted(viewModel: GameViewModel)
{
    viewModel.setPixel(2,10,filled)
    viewModel.setPixel(2,11,filled)
    viewModel.setPixel(2,12,filled)
    viewModel.setPixel(2,13,filled)
    viewModel.setPixel(3,6,filled)
    viewModel.setPixel(3,7,filled)
    viewModel.setPixel(3,8,filled)
    viewModel.setPixel(3,9,filled)
    viewModel.setPixel(3,14,filled)
    viewModel.setPixel(3,15,filled)
    viewModel.setPixel(4,5,filled)
    viewModel.setPixel(4,16,filled)
    viewModel.setPixel(5,5,filled)
    viewModel.setPixel(5,6,filled)
    viewModel.setPixel(5,7,filled)
    viewModel.setPixel(5,8,filled)
    viewModel.setPixel(5,9,filled)
    viewModel.setPixel(5,10,filled)
    viewModel.setPixel(5,11,filled)
    viewModel.setPixel(5,12,filled)
    viewModel.setPixel(5,17,filled)
    viewModel.setPixel(6,4,filled)
    viewModel.setPixel(6,8,filled)
    viewModel.setPixel(6,9,filled)
    viewModel.setPixel(6,10,filled)
    viewModel.setPixel(6,13,filled)
    viewModel.setPixel(6,17,filled)
    viewModel.setPixel(7,3,filled)
    viewModel.setPixel(7,9,filled)
    viewModel.setPixel(7,14,filled)
    viewModel.setPixel(7,17,filled)
    viewModel.setPixel(8,2,filled)
    viewModel.setPixel(8,10,filled)
    viewModel.setPixel(8,14,filled)
    viewModel.setPixel(8,17,filled)
    viewModel.setPixel(9,2,filled)
    viewModel.setPixel(9,11,filled)
    viewModel.setPixel(9,14,filled)
    viewModel.setPixel(9,17,filled)
    viewModel.setPixel(10,2,filled)
    viewModel.setPixel(10,4,filled)
    viewModel.setPixel(10,5,filled)
    viewModel.setPixel(10,7,filled)
    viewModel.setPixel(10,11,filled)
    viewModel.setPixel(10,14,filled)
    viewModel.setPixel(10,17,filled)
    viewModel.setPixel(11,2,filled)
    viewModel.setPixel(11,4,filled)
    viewModel.setPixel(11,5,filled)
    viewModel.setPixel(11,7,filled)
    viewModel.setPixel(11,11,filled)
    viewModel.setPixel(11,14,filled)
    viewModel.setPixel(11,17,filled)
    viewModel.setPixel(12,3,filled)
    viewModel.setPixel(12,7,filled)
    viewModel.setPixel(12,8,filled)
    viewModel.setPixel(12,10,filled)
    viewModel.setPixel(12,14,filled)
    viewModel.setPixel(12,17,filled)
    viewModel.setPixel(13,3,filled)
    viewModel.setPixel(13,7,filled)
    viewModel.setPixel(13,9,filled)
    viewModel.setPixel(13,13,filled)
    viewModel.setPixel(13,17,filled)
    viewModel.setPixel(14,4,filled)
    viewModel.setPixel(14,7,filled)
    viewModel.setPixel(14,9,filled)
    viewModel.setPixel(14,12,filled)
    viewModel.setPixel(14,17,filled)
    viewModel.setPixel(15,5,filled)
    viewModel.setPixel(15,6,filled)
    viewModel.setPixel(15,7,filled)
    viewModel.setPixel(15,10,filled)
    viewModel.setPixel(15,11,filled)
    viewModel.setPixel(15,16,filled)
    viewModel.setPixel(16,7,filled)
    viewModel.setPixel(16,11,filled)
    viewModel.setPixel(16,15,filled)
    viewModel.setPixel(17,6,filled)
    viewModel.setPixel(17,8,filled)
    viewModel.setPixel(17,12,filled)
    viewModel.setPixel(17,13,filled)
    viewModel.setPixel(17,14,filled)
}